# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['todo.py'],
    pathex=[],
    binaries=[],
    datas=[('clipboard.png', '.'), ('version.txt', '.'), ('cvm_defaults.json', '.')],
    hiddenimports=[
        'PIL',
        'PIL._imagingtk',
        'PIL._tkinter_finder',
        'tkinter',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'tkinter.ttk',
        'tkcalendar',
        'requests',
        'cryptography',
        'cryptography.fernet',
        'mysql.connector',
        'keyring',
        'modular_updater',
        'ai_assistant',
        'mysql_lan_manager',
        'daily_todo_manager',
        'todo_list_manager',
        'calendar_view',
        'cvm_manager',
        'cvm_client',
        'weekly_schedule_view',
        'e2e_crypto',
        'ui_utils',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['win32com', 'win32service', 'win32serviceutil'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='todo',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
)
